version: '3.7'
services:
    db1:
        build: .
        # network_mode: "host"
        # pid: "host"
        container_name: jupyter
        volumes:
          - .:/home/docker-container/jupyter_notebook
        environment:
            TZ: "Asia/Seoul"
        ports:
            - "8888:8888"
        command: bash -c 'jupyter notebook'
        hostname: jupyter